let codes = {
    'Accident': {
        1: 'Rollover/Overturn',
        2: 'Fire/Explosion',
        3: 'Immersion',
        4: 'Gas Inhalation',
        5: 'Fell/Jumped from Vehicle',
        6: 'Injured in Vehicle(Non-Collision)',
        7: 'Other Non-Collision',
        8: 'Pedestrian',
        9: 'Cyclist',
        10: 'Railway Vehicle',
        11: 'Animal',
        12: 'Motor Vehicle In-Transport',
        14: 'Parked Motor Vehicle',
        15: 'Non-Motorist',
        16: 'Non-Fixed Object',
        17: 'Non-Fixed Object',
        18: 'Non-Fixed Object',
        19: 'Building',
        20: 'Fixed Object',
        21: 'Fixed Object',
        23: 'Fixed Object',
        24: 'Fixed Object',
        25: 'Fixed Object',
        26: 'Fixed Object',
        30: 'Fixed Object',
        31: 'Fixed Object',
        32: 'Embankment',
        33: 'Embankment',
        34: 'Embankment',
        35: 'Embankment',
        38: 'Fixed Object',
        39: 'Fixed Object',
        40: 'Fixed Object',
        41: 'Fixed Object',
        42: 'Fixed Object',
        43: 'Fixed Object',
        44: 'Surface Irregularity (Potholes)',
        45: 'Working Motor Vehicle',
        46: 'Fixed Object',
        48: 'Embankment',
        49: 'Ridden Animal',
        50: 'Bridge Overhead Structure',
        51: 'Jackknife',
        52: 'Guardrail End',
        53: 'Fixed Object',
        54: 'Motor Vehicle strikes/struck by object set in motion from/by another vehicle',
        55: 'Motor Vehicle in motion outside trafficway',
        57: 'Cable Barrier',
        58: 'Ground',
        59: 'Fixed Object',
        72: 'Cargo/Equipment Loss or Damage',
        73: 'Object that had fallen from another motor vehicle',
        74: 'Road vehicle on Rails',
        91: 'Unknown',
        93: 'Unknown',
        99: 'Unknown'
    },
    'WEATHER': {
        0: 'No conditions',
        1: 'Clear',
        2: 'Rain',
        3: 'Sleet/Hail',
        4: 'Snow',
        5: 'Fog/Smog/Smoke',
        6: 'Severe Crosswinds',
        7: 'Blowind Sand/Soil/Dirt',
        8: 'Other',
        10: 'Cloudy',
        11: 'Blowing Snow',
        12: 'Freezing Rain',
        98: 'Not Reported',
        99: 'Unknown'
    },
    'DAY_WEEK': {
        1: 'Mon',
        2: 'Tue',
        3: 'Wed',
        4: 'Thur',
        5: 'Fri',
        6: 'Sat',
        7: 'Sun'
    },
    'MONTH': {
        1: 'Jan',
        2: 'Feb',
        3: 'Mar',
        4: 'Apr',
        5: 'May',
        6: 'Jun',
        7: 'Jul',
        8: 'Aug',
        9: 'Sep',
        10: 'Oct',
        11: 'Nov',
        12: 'Dec'
    },
    'State': {
        1: 'Alabama',
        2: 'Alaska',
        4: 'Arizona',
        5: 'Arkansas',
        6: 'California',
        8: 'Colorado',
        9: 'Connecticut',
        10: 'Delaware',
        11: 'District of Columbia',
        12: 'Florida',
        13: 'Georgia',
        15: 'Hawaii',
        16: 'Idaho',
        17: 'Illinois',
        18: 'Indiana',
        19: 'Iowa',
        20: 'Kansas',
        21: 'Kentucky',
        22: 'Louisiana',
        23: 'Maine',
        24: 'Maryland',
        25: 'Massachusetts',
        26: 'Michigan',
        27: 'Minnesota',
        28: 'Mississippi',
        29: 'Missouri',
        30: 'Montana',
        31: 'Nebraska',
        32: 'Nevada',
        33: 'New Hampshire',
        34: 'New Jersey',
        35: 'New Mexico',
        36: 'New York',
        37: 'North Carolina',
        38: 'North Dakota',
        39: 'Ohio',
        40: 'Oklahoma',
        41: 'Oregon',
        42: 'Pennsylvania',
        44: 'Rhode Island',
        45: 'South Carolina',
        46: 'South Dakota',
        47: 'Tennessee',
        48: 'Texas',
        49: 'Utah',
        50: 'Vermont',
        51: 'Virginia',
        53: 'Washington',
        54: 'West Virginia',
        55: 'Wisconsin',
        56: 'Wyoming',
    }
};