let codes = {
    'Accident Type': {
        1: 'Rollover/Overturn',
        2: 'Fire/Explosion',
        3: 'Immersion',
        4: 'Gas Inhalation',
        5: 'Fell/Jumped from Vehicle',
        6: 'Injured in Vehicle(Non-Collision)',
        7: 'Other Non-Collision',
        8: 'Pedestrian',
        9: 'Cyclist',
        10: 'Railway Vehicle',
        11: 'Animal',
        12: 'Motor Vehicle In-Transport',
        14: 'Parked Motor Vehicle',
        15: 'Non-Motorist',
        16: 'Falling Object',
        17: 'Boulder',
        18: 'Other Non-Fixed Object',
        19: 'Building',
        20: 'Crash Cushion',
        21: 'Bridge Pier or Support',
        23: 'Bridge Rail',
        24: 'Guardrail Face',
        25: 'Concrete Traffic Barrier',
        26: 'Other Traffic Barrier',
        30: 'Utility Pole',
        31: 'Other Pole',
        32: 'Culvert',
        33: 'Curb',
        34: 'Ditch',
        35: 'Embankment',
        38: 'Fence',
        39: 'Wall',
        40: 'Fire Hydrant',
        41: 'Shrubbery',
        42: 'Tree',
        43: 'Other Fixed Object',
        44: 'Surface Irregularity (Potholes)',
        45: 'Working Motor Vehicle',
        46: 'Traffic Signal Support',
        48: 'Snow Bank',
        49: 'Ridden Animal',
        50: 'Bridge Overhead Structure',
        51: 'Jackknife',
        52: 'Guardrail End',
        53: 'Mail Box',
        54: 'Motor Vehicle strikes/struck by object set in motion from/by another vehicle',
        55: 'Motor Vehicle in motion outside trafficway',
        57: 'Cable Barrier',
        58: 'Ground',
        59: 'Traffic Sign Support',
        72: 'Cargo/Equipment Loss or Damage',
        73: 'Object that had fallen from another motor vehicle',
        74: 'Road vehicle on Rails',
        91: 'Unknown non fixed object',
        93: 'Unknown fixed object',
        99: 'Unknown'
    },
    'WEATHER': {
        0: 'No conditions',
        1: 'Clear',
        2: 'Rain',
        3: 'Sleet/Hail',
        4: 'Snow',
        5: 'Fog/Smog/Smoke',
        6: 'Severe Crosswinds',
        7: 'Blowind Sand/Soil/Dirt',
        8: 'Other',
        10: 'Cloudy',
        11: 'Blowing Snow',
        12: 'Freezing Rain',
        98: 'Not Reported',
        99: 'Unknown'
    },
    'DAY_WEEK': {
        1: 'Mon',
        2: 'Tue',
        3: 'Wed',
        4: 'Thur',
        5: 'Fri',
        6: 'Sat',
        7: 'Sun'
    },
    'MONTH': {
        1: 'Jan',
        2: 'Feb',
        3: 'Mar',
        4: 'Apr',
        5: 'May',
        6: 'Jun',
        7: 'Jul',
        8: 'Aug',
        9: 'Sep',
        10: 'Oct',
        11: 'Nov',
        12: 'Dec'
    },

};